{% set name = "DiffPriv" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/DiffPriv-{{ version }}.tar.gz
  sha256: 135f104e825accc32e33d4d8e79777024896e038f202336b1b51fe7bb1aa21b9

build:
  number: 0
  noarch: python
  entry_points:
    - diffpriv=DiffPriv.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - numpy
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - DiffPriv
  commands:
    - pip check
    - diffpriv --help
  requires:
    - pip

about:
  home: https://github.com/Quantalabs/DiffPriv
  summary: A Differential Privacy Package
  dev_url: https://github.com/Quantalabs/DiffPriv
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Quantalabs
    - Quantum9Innovation
