{% set name = "DiffPriv" %}
{% set version = "2.0.0b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/DiffPriv-{{ version }}.tar.gz
  sha256: 1870f07dcaab4b672907338ef8aea3a860ab70e12e1e47cb425abf1a0f825032
  
build:
  number: 1
  noarch: python
  entry_points:
    - diffpriv=DiffPriv.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - DiffPriv
    - DiffPriv.mech
  commands:
    - pip check
    - diffpriv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Quantalabs/DiffPriv
  summary: A Differential Privacy Package
  dev_url: https://github.com/Quantalabs/DiffPriv
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Quantalabs
    - Quantum9Innovation
